# Generated by Django 5.2.9 on 2026-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error')], default='idle', max_length=20)),
                ('current_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.CharField(blank=True, max_length=300)),
                ('last_error', models.TextField(blank=True)),
                ('total_seen', models.PositiveIntegerField(default=0)),
                ('total_created', models.PositiveIntegerField(default=0)),
                ('total_updated', models.PositiveIntegerField(default=0)),
                ('stop_requested', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('content', models.TextField(verbose_name='Content')),
                ('polarity', models.FloatField(verbose_name='Polarity score')),
                ('subjectivity', models.FloatField(verbose_name='Subjectivity score')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('fetch_date', models.DateField(auto_now_add=True, verbose_name='Fetch date')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('published_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Published date')),
                ('source', models.TextField(verbose_name='Source link')),
            ],
            options={
                'ordering': ['-published_date', '-fetch_date', '-id'],
                'indexes': [models.Index(fields=['topic', 'published_date'], name='cnn_aggrega_topic_3025a0_idx'), models.Index(fields=['polarity'], name='cnn_aggrega_polarit_18a30e_idx'), models.Index(fields=['subjectivity'], name='cnn_aggrega_subject_3ff589_idx')],
            },
        ),
    ]
