# Generated by Django 5.2.9 on 2026-06-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cnn_aggregator.workerstate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
